# Generated by Django 3.1.7 on 2021-03-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='facebook_link',
        ),
    ]
