# Generated by Django 3.1.7 on 2021-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210321_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
