# Generated by Django 3.1.7 on 2021-03-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
