# Generated by Django 3.1.7 on 2021-03-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210326_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
    ]
